---
# tasks file for configuration
#
- name: "uncompress mediawiki archive"
  unarchive:
   src: "{{mediawiki_archive_url}}"
   dest: "{{mediawiki_directory}}"
   owner: "apache"
   group: "apache"
   remote_src: yes
   # remove mediawiki-1.xx.x/ from path
   extra_opts: --transform=s/Ë†mediawiki-[0-9\.]*\///
